version: '3.9'
services:
  eureka-server:
    image: eureka-image:v1
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - micro-net

networks:
  micro-net:
    external: true
